name: Build and Test hello-python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hello_python/requirements.txt

    - name: Build Cython extension
      run: |
        cd hello_python
        python setup_cython.py

    - name: Run tests
      run: |
        cd hello_python
        tox

    - name: Setup test suite
      run: |
        cd hello_python
        tox -vv --notest

    - name: Run test suite
      run: |
        cd hello_python
        tox --skip-pkg-install
